### ISSUE TITLE
Words cut by gif in horizontal view

### ISSUE THREAD

**Issue by damndaniel21** [axiel7/Weeb#1]
I have a tablet w/ 1920x1200p, when I tap the button in horizontal mode the letters supposed to display are barely visible. However everything else work perfectly in vertical. Nice app 👌
![Screenshot_20200123-110948](https://user-images.githubusercontent.com/60217386/72975962-fbc9ff80-3dd1-11ea-84f1-992bdda9c445.png)

**Comment by axiel7** [comment]
Thanks! I'll fix it ASAP

**Comment by axiel7** [comment]
Fixed on v0.1.2
